version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@5.1

workflows:
  build-and-push:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: "<AWS_ACCOUNT_ID>"
          region: "<AWS_REGION>"
          repo: "<ECR_REPOSITORY_NAME>"
          tag: "latest"
          auth:
            - aws-cli/setup:
                profile_name: "default"
                role_arn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME>"
